CREATE TABLE SUBJECT(
    NO VARCHAR2(4) NOT NULL,
    S_NUM VARCHAR2(2) NOT NULL,
    S_NAME VARCHAR2(30) NOT NULL,
    
    CONSTRAINT SUBJECT_NO_PK PRIMARY KEY (NO),
    CONSTRAINT SUBJECT_S_NUM_UK UNIQUE (S_NUM),
    CONSTRAINT SUBJECT_S_NAME_UK UNIQUE (S_NAME)
); --3

INSERT INTO SUBJECT VALUES('0001', '01', '컴퓨터학과');
INSERT INTO SUBJECT VALUES('0002', '02', '교육학과');
INSERT INTO SUBJECT VALUES('0003', '03', '신문방송학과');
INSERT INTO SUBJECT VALUES('0004', '04', '인터넷비즈니스과');
INSERT INTO SUBJECT VALUES('0005', '05', '기술경영과');

SELECT * FROM SUBJECT;

SELECT * FROM SUBJECT;
DROP TABLE SUBJECT;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='SUBJECT';







CREATE TABLE STUDENT (
    NO VARCHAR2(4) NOT NULL,
    SD_NUM VARCHAR2(8) NOT NULL,
    SD_NAME VARCHAR2(10) NOT NULL,
    SD_ID VARCHAR2(30) NOT NULL,
    SD_PASSWD VARCHAR2(20) NOT NULL,
    S_NUM VARCHAR2(2) NOT NULL,
    SD_BIRTH DATE NOT NULL,
    SD_PHONE VARCHAR2(11) NOT NULL,
    SD_ADDRESS VARCHAR2(30) NOT NULL,
    SD_EMAIL VARCHAR2(25) NOT NULL,
    SD_DATE DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT STUDENT_NO_PK PRIMARY KEY (NO),
    CONSTRAINT STUDENT_SD_NUM_UK UNIQUE (SD_NUM),
    CONSTRAINT STUDENT_SD_ID_UK UNIQUE (SD_ID),
    CONSTRAINT STUDENT_S_NUM_FK FOREIGN KEY (S_NUM)
        REFERENCES SUBJECT (S_NUM),
    CONSTRAINT STUDNET_SD_PHONE_UK UNIQUE (SD_PHONE),
    CONSTRAINT STUDENT_SD_EMAIL_UK UNIQUE (SD_EMAIL)
    ); --2
    
    -- 학과테이블 레코드 입력완료

INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES('0001', '06010001', '김정수', 'JAVAJSP', '1234', '01', '2000/05/07', '01012345678', '서울시 서대문구 창천동', 'ASD@ASD.NET');
    
INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES('0002', '95010002', '김수현', 'JDBCMANIA', '4321', '01', '1974/03/23', '01011112222', '서울시 서초구 양재동', '8282@LYCOS.COM');


INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES('0003', '98040001', '공지영', 'GONJI', '2580', '04', '1978/03/23', '01015412580', '부산광역시 해운대구 반송동', '2580@YAHOO.COM');
    
INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES( '0004', '02050001', '조수영', 'WATER', '1357', '05', '1980/08/15', '01098765432', '대전광역시 중구 은행동', 'WATER@HANMAIL.NET');
    
    
INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES('0005', '94040002', '최경란', 'NOVEL', '2222', '04', '1973/02/01', '01011119999', '경기도 수원시 장안구 이목동', 'NOVELJOA@NAVER.COM');
    
INSERT INTO STUDENT(NO, SD_NUM, SD_NAME, SD_ID, SD_PASSWD, S_NUM, SD_BIRTH, SD_PHONE, SD_ADDRESS, SD_EMAIL)
VALUES('0006', '08020001', '안익태', 'KOREA', '5544', '02', '1906/12/05', '01062231520', '경기도 남양주시 오남읍', 'IKTAE06@KOREA.COM');
SELECT * FROM STUDENT;

DROP TABLE STUDENT;
SELECT * FROM STUDENT;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='STUDENT';





CREATE TABLE LESSON(
    NO VARCHAR2(4) NOT NULL,
    L_ABBRE VARCHAR2(2) NOT NULL,
    L_NAME VARCHAR2(16) NOT NULL,
    
    CONSTRAINT LESSON_NO_PK PRIMARY KEY (NO),
    CONSTRAINT LESSON_L_ABBRE_UK UNIQUE (L_ABBRE),
    CONSTRAINT LESSON_L_NAME_UK UNIQUE (L_NAME)
);
  
INSERT INTO LESSON VALUES ('0001', 'K', '국어');
INSERT INTO LESSON VALUES ('0002', 'M', '수학');
INSERT INTO LESSON VALUES ('0003', 'E', '영어');
INSERT INTO LESSON VALUES ('0004', 'H', '역사');
INSERT INTO LESSON VALUES ('0005', 'P', '프로그래밍');
INSERT INTO LESSON VALUES ('0006', 'D', '데이터베이스');
INSERT INTO LESSON VALUES ('0007', 'ED', '교육학이론');
INSERT INTO LESSON VALUES ('0008', 'IN', '솩솩의드럼교실');
INSERT INTO LESSON VALUES ('0009', 'KA', '병영체험');
SELECT * FROM LESSON;
  
  
SELECT * FROM LESSON;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='LESSON';
DROP TABLE LESSON; --1







CREATE TABLE TRAINEE (
    NO VARCHAR2(4) NOT NULL,
    SD_NUM VARCHAR2(8) NOT NULL,
    L_ABBRE VARCHAR2(2) NOT NULL,
    T_SECTION VARCHAR2(10) NOT NULL,
    T_DATE DATE DEFAULT SYSDATE NOT NULL,
    
    CONSTRAINT TRAINEE_NO_PK PRIMARY KEY (NO),
    CONSTRAINT TRAINEE_SD_NUM_FK FOREIGN KEY (SD_NUM)
        REFERENCES STUDENT (SD_NUM),
    CONSTRAINT TRAINEE_L_ABBRE_FK FOREIGN KEY (L_ABBRE)
        REFERENCES LESSON(L_ABBRE)
); --4


INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION) 
VALUES ('0001', '06010001', 'K', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION) 
VALUES ('0002', '06010001', 'H', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0004', '06010001', 'KA', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0005', '95010002', 'M', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION) 
VALUES ('0006', '95010002', 'P', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0007', '95010002', 'IN', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0008', '98040001', 'E', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0009', '95010002', 'ED', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION)
VALUES ('0010', '95010002', 'KA', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0011', '98040001', 'H', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0012', '98040001', 'ED', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0013', '98040001', 'IN', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0014', '02050001', 'P', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0015', '02050001', 'D', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0016', '02050001', 'KA', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0017', '94040002', 'D', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0018', '94040002', 'P', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0019', '94040002', 'IN', 'CULTURE');

INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0020', '08020001', 'IN', 'MAJOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0021', '08020001', 'H', 'MINOR');
INSERT INTO TRAINEE(NO, SD_NUM, L_ABBRE, T_SECTION
)VALUES ('0022', '08020001', 'ED', 'CULTURE');
SELECT * FROM TRAINEE;
DESC TRAINEE;




ALTER TABLE TRAINEE DROP CONSTRAINT TRAINEE_T_SECTION_UK;
SELECT * FROM TRAINEE;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='TRAINEE';
DROP TABLE TRAINEE;


-- 1-1 사원번호, 사원명, 입사일과 부서명을 출력하도록 쿼리문 작성해 주세요
SELECT * FROM EMP;

SELECT EMPNO, ENAME, HIREDATE, D.DNAME
FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO;

-- 1-2 학번, 학생명과 학과명을 출력하도록 쿼리문 작성해 주세요.
SELECT SD_NUM 학번, SD_NAME 학생명, S_NAME 학과명
FROM SUBJECT SUB INNER JOIN STUDENT STU
ON SUB.S_NUM = STU.S_NUM;